name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      # stack-action takes care of `stack build` and caching the results
      - uses: freckle/stack-action@v5
        with:
          # hakyll 4.16.8.0 will not build with --pedantic and that's the default (with --fast, too)
          stack-build-arguments: --fast

      - name: Build
        run: |
         stack exec site build

      - name: Upload
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
